apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-19T16:56:17Z"
  generation: 11
  labels:
    app: frontend-image-portal
  name: frontend-image-portal
  namespace: default
  resourceVersion: "2286754"
  selfLink: /apis/apps/v1/namespaces/default/deployments/frontend-image-portal
  uid: 9bea11af-3adc-11ea-9bb7-42010a8400a8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend-image-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-image-portal
    spec:
      containers:
      - env:
        - name: UPLOAD_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: UPLOAD_HOSTNAME
              name: frontend-image-portal-config
        - name: UPLOAD_PORT
          valueFrom:
            configMapKeyRef:
              key: UPLOAD_PORT
              name: frontend-image-portal-config
        - name: CATALOGUE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: CATALOGUE_HOSTNAME
              name: frontend-image-portal-config
        - name: CATALOGUE_PORT
          valueFrom:
            configMapKeyRef:
              key: CATALOGUE_PORT
              name: frontend-image-portal-config
        - name: USERMANAGE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: USERMANAGE_HOSTNAME
              name: frontend-image-portal-config
        - name: USERMANAGE_PORT
          valueFrom:
            configMapKeyRef:
              key: USERMANAGE_PORT
              name: frontend-image-portal-config
        - name: FLASK_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: FLASK_SECRET_KEY
              name: frontend-image-portal-config
        - name: ANALYSIS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: ANALYSIS_HOSTNAME
              name: frontend-image-portal-config
        - name: ANALYSIS_PORT
          valueFrom:
            configMapKeyRef:
              key: ANALYSIS_PORT
              name: frontend-image-portal-config
        - name: COMMENTS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: COMMENTS_HOSTNAME
              name: frontend-image-portal-config
        - name: COMMENTS_PORT
          valueFrom:
            configMapKeyRef:
              key: COMMENTS_PORT
              name: frontend-image-portal-config
        image: registry.hub.docker.com/slosquad42/image_portal_frontend:latest
        imagePullPolicy: Always
        name: image-portal-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-19T16:56:17Z"
    lastUpdateTime: "2020-01-19T16:56:30Z"
    message: ReplicaSet "frontend-image-portal-7c7cbc4d4c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-20T00:01:23Z"
    lastUpdateTime: "2020-01-20T00:01:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
